// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNYtNTKI4EEt7EXjaNcuL9saAV0VSPlt4',
    appId: '1:82953668792:web:ec0e628d1b5710de65cc4d',
    messagingSenderId: '82953668792',
    projectId: 'deliver-d327d',
    authDomain: 'deliver-d327d.firebaseapp.com',
    storageBucket: 'deliver-d327d.appspot.com',
    measurementId: 'G-MFHQYVQCLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoWZqWS5NGG7yyD7DtAORJNWPe0BL3D64',
    appId: '1:82953668792:android:a1ceeab80f4b905065cc4d',
    messagingSenderId: '82953668792',
    projectId: 'deliver-d327d',
    storageBucket: 'deliver-d327d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX8FvnkBY5reYKDhRY2hyiSHldLcBZ8nw',
    appId: '1:82953668792:ios:91bade0acd46cfc565cc4d',
    messagingSenderId: '82953668792',
    projectId: 'deliver-d327d',
    storageBucket: 'deliver-d327d.appspot.com',
    iosClientId: '82953668792-m2phe5ju674mpnli8asdbugcebbm7cij.apps.googleusercontent.com',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX8FvnkBY5reYKDhRY2hyiSHldLcBZ8nw',
    appId: '1:82953668792:ios:91bade0acd46cfc565cc4d',
    messagingSenderId: '82953668792',
    projectId: 'deliver-d327d',
    storageBucket: 'deliver-d327d.appspot.com',
    iosClientId: '82953668792-m2phe5ju674mpnli8asdbugcebbm7cij.apps.googleusercontent.com',
    iosBundleId: 'com.example.delivery',
  );
}
