// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANCC5ZYQQ7-yHFfPYzWDHwEbsXtr1lsE',
    appId: '1:1031117097845:web:24354e95f235af65daa13c',
    messagingSenderId: '1031117097845',
    projectId: 'finalproject-5854f',
    authDomain: 'finalproject-5854f.firebaseapp.com',
    storageBucket: 'finalproject-5854f.appspot.com',
    measurementId: 'G-WZQV65V4K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjbwwSYYlv2lYVUQGorX7hqLxYC-gZL1Q',
    appId: '1:1031117097845:android:ce456efd29016197daa13c',
    messagingSenderId: '1031117097845',
    projectId: 'finalproject-5854f',
    storageBucket: 'finalproject-5854f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIVAVJGA1XCyt5-ApFtkmejqhS54_rjiI',
    appId: '1:1031117097845:ios:f03ad06a52ec740edaa13c',
    messagingSenderId: '1031117097845',
    projectId: 'finalproject-5854f',
    storageBucket: 'finalproject-5854f.appspot.com',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIVAVJGA1XCyt5-ApFtkmejqhS54_rjiI',
    appId: '1:1031117097845:ios:f03ad06a52ec740edaa13c',
    messagingSenderId: '1031117097845',
    projectId: 'finalproject-5854f',
    storageBucket: 'finalproject-5854f.appspot.com',
    iosBundleId: 'com.example.delivery',
  );
}
